spring:
  profiles:
    active: test

logging:
  level:
    com.br.bercalini: TRACE
    com.br.bercalini.heldesk: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

jwt:
  secret: StringUsadaParaGerarToken
  expiration: 640800000